Repository fproldan/erpnext, pull requests merged in 2022-05, with the labels that each got.

#170 Release Notes 1.4
  erpnext/patches.txt
  erpnext/patches/v13_0/release_1_4.py
Labels: backport diamoerp-staging

#168 Nuevos opciones para el campo "Tipo de dólar"
  erpnext/setup/doctype/currency_exchange/currency_exchange.py
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#180 feat: branding
  erpnext/hooks.py
  erpnext/hr/doctype/daily_work_summary/test_data/test-reply.raw
  erpnext/setup/install.py
Labels: backport jphlions-staging

#173 Traducciones 1.5
  erpnext/buying/report/supplier_quotation_comparison/supplier_quotation_comparison.js
  erpnext/buying/report/supplier_quotation_comparison/supplier_quotation_comparison.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#179 [Goldnutrition] Accounts Receivable & Payable - Monto Pendiente USD column
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
Labels: backport diamoerp-staging

#188 Traducciones
  erpnext/buying/doctype/supplier/supplier.json
  erpnext/projects/report/project_summary/project_summary.py
  erpnext/selling/doctype/customer/customer.json
  erpnext/translations/es.csv
Labels: backport diamoerp-develop, backport jphlions-develop, backport jphlions-staging

#193 [Trans] Solicitud de Materiales > Solicitud
  erpnext/translations/es.csv
Labels: backport jphlions-staging

#196 Maestros
  erpnext/buying/doctype/configuracion_de_compras/__init__.py
  erpnext/buying/doctype/configuracion_de_compras/configuracion_de_compras.js
  erpnext/buying/doctype/configuracion_de_compras/configuracion_de_compras.json
  erpnext/buying/doctype/configuracion_de_compras/configuracion_de_compras.py
  erpnext/buying/doctype/configuracion_de_compras/test_configuracion_de_compras.py
  erpnext/buying/doctype/supplier/supplier.json
  erpnext/buying/workspace/buying/buying.json
  erpnext/selling/doctype/customer/customer.json
Labels: backport jphlions-staging

#156 Flujo de Fondo
  erpnext/accounts/utils.py
  erpnext/accounts/workspace/accounting/accounting.json
  erpnext/public/js/bank_reconciliation_tool/dialog_manager.js
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#211 feat: update docs link
  erpnext/patches.txt
  erpnext/patches/v13_0/update_docs_link.py
  erpnext/setup/install.py
Labels: backport diamoerp-staging
