Repository fproldan/erpnext, pull requests merged in 2022-06, with the labels that each got.

#219 feat: accounts sumary
  erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.py
Labels: backport diamoerp-staging

#221 Fix reporte
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
Labels: backport diamoerp-staging

#224 fix
  erpnext/accounts/report/accounts_receivable/accounts_receivable.py
Labels: backport diamoerp-staging

#234 Permisos para HolidayList
  erpnext/hr/doctype/holiday_list/holiday_list.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#210 Trans 1.5.0
  erpnext/controllers/accounts_controller.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#239 Valores por defecto
  erpnext/setup/setup_wizard/operations/defaults_setup.py
  erpnext/setup/setup_wizard/operations/install_fixtures.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#232 Sales commission payout
  erpnext/accounts/doctype/payment_entry/payment_entry.py
  erpnext/payroll/doctype/contributions/__init__.py
  erpnext/payroll/doctype/contributions/contributions.json
  erpnext/payroll/doctype/contributions/contributions.py
  erpnext/payroll/doctype/payroll_settings/payroll_settings.json
  erpnext/payroll/doctype/process_sales_commission/__init__.py
  erpnext/payroll/doctype/process_sales_commission/process_sales_commission.js
  erpnext/payroll/doctype/process_sales_commission/process_sales_commission.json
  erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
  erpnext/payroll/doctype/process_sales_commission/test_process_sales_commission.py
  erpnext/payroll/doctype/sales_commission/__init__.py
  erpnext/payroll/doctype/sales_commission/sales_commission.js
  erpnext/payroll/doctype/sales_commission/sales_commission.json
  erpnext/payroll/doctype/sales_commission/sales_commission.py
  erpnext/payroll/doctype/sales_commission/sales_commission_list.js
  erpnext/payroll/doctype/sales_commission/test_sales_commission.py
  erpnext/payroll/workspace/payroll/payroll.json
  erpnext/selling/doctype/process_sales_commission/__init__.py
  erpnext/selling/doctype/selling_settings/selling_settings.json
  erpnext/selling/workspace/selling/selling.json
  erpnext/setup/doctype/sales_person/sales_person.json
  erpnext/setup/setup_wizard/operations/install_fixtures.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#243 No funciona el campo de buscar productos en BOM
  erpnext/manufacturing/doctype/bom/bom.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#257 Releases Notes 1.4.1
  erpnext/patches.txt
  erpnext/patches/v13_0/release_1_4_1.py
Labels: backport diamoerp-staging

#231 [JPH] Issue 11 - Generar alerta de items no recibidos
  erpnext/buying/doctype/purchase_order/purchase_order.json
  erpnext/buying/notification/__init__.py
  erpnext/buying/notification/items_no_recibidos/__init__.py
  erpnext/buying/notification/items_no_recibidos/items_no_recibidos.json
  erpnext/buying/notification/items_no_recibidos/items_no_recibidos.md
  erpnext/buying/notification/items_no_recibidos/items_no_recibidos.py
  erpnext/buying/report/reclamo_a_proveedor/__init__.py
  erpnext/buying/report/reclamo_a_proveedor/reclamo_a_proveedor.js
  erpnext/buying/report/reclamo_a_proveedor/reclamo_a_proveedor.json
  erpnext/buying/report/reclamo_a_proveedor/reclamo_a_proveedor.py
  erpnext/buying/workspace/buying/buying.json
Labels: backport jphlions-staging
