Repository fproldan/erpnext, pull requests merged in 2022-11, with the labels that each got.

#442 [JPH] [Compras] Ocultar "Mas Informacion" en OC
  erpnext/buying/doctype/purchase_order/purchase_order.json
Labels: backport jphlions-staging

#439 fix: difference amount calculation on payment reconciliation
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.js
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#435 [JPH] [Issue 33] Secuencia
  erpnext/patches.txt
  erpnext/patches/v13_0/set_default_naming_series.py
  erpnext/public/js/controllers/transaction.js
  erpnext/setup/doctype/company/company.py
  erpnext/setup/doctype/naming_series/naming_series.py
Labels: backport jphlions-staging

#264 [JPH Issue 2] Agrupar solicitud de pedido
  erpnext/stock/doctype/material_request/material_request.js
  erpnext/stock/doctype/material_request/material_request.json
Labels: backport jphlions-staging

#454 [Compras JPH Issue 37] Mejora creacion OC desde Solicitud
  erpnext/stock/doctype/material_request/material_request.js
  erpnext/stock/doctype/material_request/material_request.py
Labels: backport jphlions-staging

#457 [Compras] [JPH Issue 32] Consultar quién debe autorizar los pedidos
  erpnext/buying/doctype/buying_settings/buying_settings.json
  erpnext/buying/workspace/buying/buying.json
Labels: backport jphlions-staging

#460 [Compras] [JPH Issue 38] Ocultar campo en Categoria de activos
  erpnext/assets/doctype/asset_category_account/asset_category_account.json
Labels: backport jphlions-staging

#462 [Compras] [JPH Issue 37] [Fix] Mejora creacion OC desde Solicitud
  erpnext/stock/doctype/material_request/material_request.py
Labels: backport jphlions-staging

#412 feat: Payment Terms Status report (backport #29137)
  erpnext/selling/report/payment_terms_status_for_sales_order/__init__.py
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.js
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.json
  erpnext/selling/report/payment_terms_status_for_sales_order/payment_terms_status_for_sales_order.py
  erpnext/selling/report/payment_terms_status_for_sales_order/test_payment_terms_status_for_sales_order.py
  erpnext/selling/workspace/selling/selling.json
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#456 Maximo de adjuntos
  erpnext/accounts/doctype/c_form/c_form.json
  erpnext/accounts/doctype/cheque_print_template/cheque_print_template.json
  erpnext/healthcare/doctype/patient/patient.json
  erpnext/hr/doctype/leave_application/leave_application.json
  erpnext/hr/doctype/upload_attendance/upload_attendance.json
  erpnext/projects/doctype/project/project.json
  erpnext/projects/doctype/task/task.json
  erpnext/selling/doctype/quotation/quotation.json
  erpnext/setup/doctype/item_group/item_group.json
  erpnext/stock/doctype/batch/batch.json
  erpnext/stock/doctype/item/item.json
  erpnext/stock/doctype/price_list/price_list.json
  erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.json
  erpnext/utilities/doctype/rename_tool/rename_tool.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#469 Fix minor portal
  erpnext/portal/utils.py
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#473 Grupo de proveedor por defecto en portal
  erpnext/portal/utils.py
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#467 [JPH Issue 41] Facturas de Venta Normal a mi Pyme
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
  erpnext/public/js/utils.js
Labels: backport jphlions-staging

#431 Optimización y espacio
  erpnext/crm/doctype/opportunity/opportunity.json
  erpnext/telephony/doctype/call_log/call_log.json
Labels: backport diamoerp-staging

#459 Usuarios Reducidos - Ventas
  erpnext/crm/doctype/social_media_post/social_media_post.json
  erpnext/selling/doctype/product_bundle/product_bundle.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#483 Translations 17/11
  erpnext/assets/doctype/asset/asset.js
  erpnext/templates/pages/rfq.html
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#487 Translations Asset
  erpnext/assets/doctype/asset/asset.js
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#404 Bump to v13.16.0
  erpnext/__init__.py
  erpnext/accounts/doctype/account/account_tree.js
  erpnext/accounts/doctype/accounts_settings/accounts_settings.py
  erpnext/accounts/doctype/party_link/party_link.py
  erpnext/accounts/doctype/period_closing_voucher/period_closing_voucher.py
  erpnext/accounts/doctype/period_closing_voucher/test_period_closing_voucher.py
  erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py
  erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.json
  erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
  erpnext/accounts/party.py
  erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.js
  erpnext/assets/doctype/asset_value_adjustment/asset_value_adjustment.py
  erpnext/buying/doctype/supplier/supplier.js
  erpnext/buying/doctype/supplier/supplier.py
  erpnext/controllers/buying_controller.py
  erpnext/controllers/stock_controller.py
  erpnext/controllers/taxes_and_totals.py
  erpnext/hr/doctype/employee_advance/employee_advance.py
  erpnext/hr/doctype/employee_advance/test_employee_advance.py
  erpnext/hr/doctype/expense_claim/expense_claim.js
  erpnext/hr/doctype/expense_claim/expense_claim.json
  erpnext/hr/doctype/shift_assignment/shift_assignment.py
  erpnext/manufacturing/doctype/job_card/job_card.py
  erpnext/manufacturing/doctype/production_plan/production_plan.js
  erpnext/manufacturing/doctype/work_order/work_order.js
  erpnext/manufacturing/doctype/work_order/work_order.json
  erpnext/manufacturing/doctype/work_order_operation/work_order_operation.json
  erpnext/manufacturing/report/cost_of_poor_quality_report/cost_of_poor_quality_report.py
  erpnext/public/js/controllers/buying.js
  erpnext/public/js/controllers/taxes_and_totals.js
  erpnext/public/js/controllers/transaction.js
  erpnext/public/js/utils.js
  erpnext/regional/india/utils.py
  erpnext/selling/doctype/customer/customer.js
  erpnext/selling/doctype/customer/customer.py
  erpnext/selling/page/point_of_sale/pos_item_cart.js
  erpnext/setup/doctype/company/company.js
  erpnext/setup/doctype/company/company.json
  erpnext/setup/doctype/company/company.py
  erpnext/stock/doctype/material_request/material_request.py
  erpnext/stock/doctype/material_request_item/material_request_item.json
  erpnext/stock/doctype/purchase_receipt/test_purchase_receipt.py
  erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
  erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.json
  erpnext/stock/doctype/repost_item_valuation/repost_item_valuation.py
  erpnext/stock/doctype/repost_item_valuation/test_repost_item_valuation.py
  erpnext/stock/doctype/stock_reposting_settings/stock_reposting_settings.json
  erpnext/stock/get_item_details.py
  erpnext/stock/page/warehouse_capacity_summary/warehouse_capacity_summary.html
  erpnext/stock/page/warehouse_capacity_summary/warehouse_capacity_summary.js
  erpnext/stock/page/warehouse_capacity_summary/warehouse_capacity_summary_header.html
  erpnext/stock/report/total_stock_summary/total_stock_summary.js
  erpnext/stock/report/total_stock_summary/total_stock_summary.py
  erpnext/stock/report/warehouse_wise_item_balance_age_and_value/warehouse_wise_item_balance_age_and_value.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#386 Trans 1.6.0
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#501 [JPH] feat: hide party type
  erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.js
Labels: backport jphlions-staging
