Repository fproldan/erpnext, pull requests merged in 2022-02, with the labels that each got.

#66 Estados de doctype sin traducir
  erpnext/translations/es.csv
Labels: backport diamoerp-staging

#67 Entrada de Pago - Ocultar la seccion GST details
  erpnext/patches.txt
  erpnext/patches/v13_0/create_gst_payment_entry_fields.py
  erpnext/patches/v13_0/delete_gst_payment_entry_fields.py
Labels: backport diamoerp-staging

#69 Campos obligatorios conciliación cheque
  erpnext/public/js/bank_reconciliation_tool/dialog_manager.js
Labels: backport diamoerp-staging

#58 Translations 2
  erpnext/translations/es.csv
Labels: backport diamoerp-staging

#74 Permisos de rol para Driver
  erpnext/hr/doctype/driver/driver.json
Labels: backport diamoerp-staging

#71 Quick entry de proveedor
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/buying/doctype/buying_settings/buying_settings.js
  erpnext/buying/doctype/buying_settings/buying_settings.json
  erpnext/buying/doctype/buying_settings/buying_settings.py
  erpnext/buying/doctype/supplier/supplier.json
  erpnext/public/js/utils/supplier_quick_entry.js
Labels: backport diamoerp-staging

#75 Cambio de permiso por defecto
  erpnext/accounts/doctype/mode_of_payment/mode_of_payment.json
  erpnext/patches.txt
Labels: backport diamoerp-staging

#80 hotfix: indentation
  erpnext/controllers/accounts_controller.py
Labels: backport diamoerp-staging, backport diamoerp-develop

#81 hotfix: indentation
  erpnext/controllers/accounts_controller.py
Labels: backport diamoerp-staging, backport diamoerp-develop

#76 Error al crear compañía
  erpnext/patches.txt
  erpnext/patches/v13_0/add_transit_warehouse_type.py
  erpnext/setup/doctype/company/company.js
  erpnext/setup/doctype/company/company.py
  erpnext/setup/setup_wizard/operations/install_fixtures.py
  erpnext/stock/doctype/stock_entry/stock_entry.js
  erpnext/stock/doctype/warehouse/warehouse.json
Labels: backport diamoerp-staging

#85 Traducciones de dos apartados
  erpnext/setup/default_success_action.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging

#84 Traducción de Shortcut
  erpnext/translations/es.csv
Labels: backport diamoerp-staging

#91 Accounting Dimension label en purchase invoice y purchase order item
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
  erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
Labels: backport diamoerp-staging

#93 Ocultamiento de sección de compra
  erpnext/accounts/doctype/purchase_invoice/purchase_invoice.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#98 fix: remove sales payment summary from workspace
  erpnext/accounts/workspace/accounting/accounting.json
  erpnext/patches.txt
  erpnext/patches/v13_0/remove_report.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging
