Repository fproldan/erpnext, pull requests merged in 2022-03, with the labels that each got.

#102 Traducciones o cambio de texto reporte bancario
  erpnext/accounts/report/bank_reconciliation_statement/bank_reconciliation_statement.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#103 Asignar nombre luego de validar
  erpnext/accounts/doctype/sales_invoice/sales_invoice.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#116 Mejorar dos traducciones y label
  erpnext/translations/es.csv
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#117 Eliminar formatos de impresión
  erpnext/accounts/doctype/pos_invoice/pos_invoice.js
  erpnext/accounts/doctype/sales_invoice/sales_invoice.js
  erpnext/accounts/print_format/sales_auditing_voucher/__init__.py
  erpnext/accounts/print_format/sales_auditing_voucher/sales_auditing_voucher.html
  erpnext/accounts/print_format/sales_auditing_voucher/sales_auditing_voucher.json
  erpnext/accounts/print_format/sales_invoice_return/__init__.py
  erpnext/accounts/print_format/sales_invoice_return/sales_invoice_return.html
  erpnext/accounts/print_format/sales_invoice_return/sales_invoice_return.json
  erpnext/patches.txt
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#128 feat: Release Note 1.3
  erpnext/patches.txt
  erpnext/patches/v13_0/release_1_3.py
Labels: backport diamoerp-staging

#94 Obtener el precio del dolar diariamente
  erpnext/hooks.py
  erpnext/setup/doctype/currency_exchange/currency_exchange.py
Labels: backport diamoerp-staging, backport diamoerp-develop, backport jphlions-staging

#126 Error al personalizar un worskpace
  erpnext/education/workspace/education/education.json
  erpnext/healthcare/workspace/healthcare/healthcare.json
  erpnext/hr/workspace/hr/hr.json
  erpnext/loan_management/workspace/loan_management/loan_management.json
  erpnext/manufacturing/workspace/manufacturing/manufacturing.json
  erpnext/patches.txt
  erpnext/patches/v13_0/fix_workspace_links.py
  erpnext/payroll/workspace/payroll/payroll.json
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging

#121 Google Maps API - Hoja de Ruta
  erpnext/patches.txt
  erpnext/patches/v13_0/add_conversion_factor.py
  erpnext/setup/doctype/global_defaults/global_defaults.js
  erpnext/setup/setup_wizard/operations/install_fixtures.py
  erpnext/stock/doctype/delivery_trip/delivery_trip.js
  erpnext/stock/doctype/delivery_trip/delivery_trip.json
  erpnext/stock/doctype/delivery_trip/delivery_trip.py
  erpnext/translations/es.csv
Labels: backport diamoerp-staging

#125 Mercadopago
  erpnext/domains/mercadolibre.py
  erpnext/domains/mercadopago.py
  erpnext/hooks.py
  erpnext/patches.txt
  erpnext/patches/v13_0/create_mercadopago_domain.py
  erpnext/setup/setup_wizard/operations/install_fixtures.py
Labels: backport diamoerp-staging, backport jphlions-develop, backport jphlions-staging
